"""팀 이름 한국어 표기.

ESPN·MLB 공식 기록은 영어 이름이라 화면에만 한국어로 바꿔 보여준다.
사전에 없는 팀은 영어 그대로 둔다. (대표팀 Elo 비교 등 안쪽 계산은 영어 이름을 그대로 쓴다)
"""

from __future__ import annotations

import re
import unicodedata

MLB = {
    "Arizona Diamondbacks": "애리조나", "Atlanta Braves": "애틀랜타", "Baltimore Orioles": "볼티모어",
    "Boston Red Sox": "보스턴", "Chicago Cubs": "시카고 컵스", "Chicago White Sox": "시카고 화이트삭스",
    "Cincinnati Reds": "신시내티", "Cleveland Guardians": "클리블랜드", "Colorado Rockies": "콜로라도",
    "Detroit Tigers": "디트로이트", "Houston Astros": "휴스턴", "Kansas City Royals": "캔자스시티",
    "Los Angeles Angels": "LA 에인절스", "Los Angeles Dodgers": "LA 다저스", "Miami Marlins": "마이애미",
    "Milwaukee Brewers": "밀워키", "Minnesota Twins": "미네소타", "New York Mets": "뉴욕 메츠",
    "New York Yankees": "뉴욕 양키스", "Athletics": "애슬레틱스", "Oakland Athletics": "애슬레틱스",
    "Philadelphia Phillies": "필라델피아", "Pittsburgh Pirates": "피츠버그", "San Diego Padres": "샌디에이고",
    "San Francisco Giants": "샌프란시스코", "Seattle Mariners": "시애틀", "St. Louis Cardinals": "세인트루이스",
    "Tampa Bay Rays": "탬파베이", "Texas Rangers": "텍사스", "Toronto Blue Jays": "토론토",
    "Washington Nationals": "워싱턴",
}

CLUBS = {
    # 잉글랜드
    "Arsenal": "아스널", "Aston Villa": "애스턴 빌라", "Bournemouth": "본머스", "AFC Bournemouth": "본머스",
    "Brentford": "브렌트퍼드", "Brighton & Hove Albion": "브라이턴", "Brighton": "브라이턴", "Burnley": "번리",
    "Chelsea": "첼시", "Crystal Palace": "크리스털 팰리스", "Everton": "에버턴", "Fulham": "풀럼",
    "Leeds United": "리즈", "Leicester City": "레스터", "Liverpool": "리버풀", "Manchester City": "맨시티",
    "Manchester United": "맨유", "Newcastle United": "뉴캐슬", "Nottingham Forest": "노팅엄",
    "Southampton": "사우샘프턴", "Sunderland": "선덜랜드", "Tottenham Hotspur": "토트넘", "West Ham United": "웨스트햄",
    "Wolverhampton Wanderers": "울버햄튼", "Ipswich Town": "입스위치", "Sheffield United": "셰필드 유나이티드",
    "Norwich City": "노리치", "Watford": "왓퍼드", "Middlesbrough": "미들즈브러", "Coventry City": "코번트리",
    "Hull City": "헐 시티", "West Bromwich Albion": "웨스트브롬", "Stoke City": "스토크", "Luton Town": "루턴",
    # 스페인
    "Real Madrid": "레알 마드리드", "Barcelona": "바르셀로나", "Atletico Madrid": "아틀레티코 마드리드",
    "Atlético Madrid": "아틀레티코 마드리드", "Athletic Club": "아틀레틱 빌바오", "Real Sociedad": "레알 소시에다드",
    "Real Betis": "레알 베티스", "Villarreal": "비야레알", "Valencia": "발렌시아", "Sevilla": "세비야",
    "Getafe": "헤타페", "Girona": "지로나", "Celta Vigo": "셀타 비고", "Osasuna": "오사수나",
    "Rayo Vallecano": "라요 바예카노", "Mallorca": "마요르카", "Alaves": "알라베스", "Deportivo Alaves": "알라베스",
    "Espanyol": "에스파뇰", "Las Palmas": "라스팔마스", "Leganes": "레가네스", "Real Valladolid": "바야돌리드",
    "Levante": "레반테", "Elche": "엘체", "Real Oviedo": "오비에도", "Racing Santander": "라싱",
    # 이탈리아
    "Internazionale": "인테르", "Inter Milan": "인테르", "AC Milan": "AC 밀란", "Juventus": "유벤투스",
    "Napoli": "나폴리", "AS Roma": "AS 로마", "Roma": "AS 로마", "Lazio": "라치오", "Atalanta": "아탈란타",
    "Fiorentina": "피오렌티나", "Bologna": "볼로냐", "Torino": "토리노", "Genoa": "제노아", "Udinese": "우디네세",
    "Lecce": "레체", "Cagliari": "칼리아리", "Parma": "파르마", "Como": "코모", "Empoli": "엠폴리",
    "Hellas Verona": "베로나", "Verona": "베로나", "Monza": "몬차", "Venezia": "베네치아", "Sassuolo": "사수올로",
    "Pisa": "피사", "Cremonese": "크레모네세", "Frosinone": "프로시노네", "Salernitana": "살레르니타나",
    # 독일
    "Bayern Munich": "바이에른 뮌헨", "Borussia Dortmund": "도르트문트", "Bayer Leverkusen": "레버쿠젠",
    "RB Leipzig": "라이프치히", "Eintracht Frankfurt": "프랑크푸르트", "VfB Stuttgart": "슈투트가르트",
    "SC Freiburg": "프라이부르크", "VfL Wolfsburg": "볼프스부르크", "Borussia Monchengladbach": "묀헨글라트바흐",
    "Union Berlin": "우니온 베를린", "1. FC Union Berlin": "우니온 베를린", "Werder Bremen": "베르더 브레멘",
    "TSG Hoffenheim": "호펜하임", "Hoffenheim": "호펜하임", "FC Augsburg": "아우크스부르크", "Augsburg": "아우크스부르크",
    "Mainz": "마인츠", "Mainz 05": "마인츠", "1. FC Heidenheim 1846": "하이덴하임", "Heidenheim": "하이덴하임",
    "St. Pauli": "장크트파울리", "FC St. Pauli": "장크트파울리", "Holstein Kiel": "홀슈타인 킬", "VfL Bochum": "보훔",
    "1. FC Koln": "쾰른", "FC Cologne": "쾰른", "Hamburg SV": "함부르크", "Hamburger SV": "함부르크",
    "Schalke 04": "샬케", "Hertha Berlin": "헤르타", "SC Paderborn 07": "파더보른", "Paderborn": "파더보른",
    # 프랑스
    "Paris Saint-Germain": "파리 생제르맹", "Marseille": "마르세유", "AS Monaco": "모나코", "Monaco": "모나코",
    "Lille": "릴", "Lyon": "리옹", "Nice": "니스", "Lens": "랑스", "Rennes": "렌", "Stade Rennais": "렌",
    "Strasbourg": "스트라스부르", "Nantes": "낭트", "Toulouse": "툴루즈", "Brest": "브레스트", "Stade Brestois": "브레스트",
    "Reims": "랭스", "Montpellier": "몽펠리에", "Auxerre": "오세르", "AJ Auxerre": "오세르", "Angers": "앙제",
    "Le Havre": "르아브르", "Le Havre AC": "르아브르", "Saint-Etienne": "생테티엔", "Lorient": "로리앙", "Metz": "메스",
    "Paris FC": "파리 FC",
    # 유럽 대회 단골
    "Benfica": "벤피카", "FC Porto": "포르투", "Porto": "포르투", "Sporting CP": "스포르팅", "Sporting Lisbon": "스포르팅",
    "Ajax": "아약스", "Ajax Amsterdam": "아약스", "PSV Eindhoven": "PSV", "PSV": "PSV", "Feyenoord": "페예노르트",
    "Celtic": "셀틱", "Rangers": "레인저스", "Galatasaray": "갈라타사라이", "Fenerbahce": "페네르바체",
    "Besiktas": "베식타스", "Club Brugge": "클럽 브뤼헤", "Red Bull Salzburg": "잘츠부르크", "Shakhtar Donetsk": "샤흐타르",
    "Olympiacos": "올림피아코스", "FC Copenhagen": "코펜하겐", "Slavia Prague": "슬라비아 프라하",
    "Sparta Prague": "스파르타 프라하", "Dinamo Zagreb": "디나모 자그레브", "Young Boys": "영 보이스",
    # J리그
    "Vissel Kobe": "비셀 고베", "Gamba Osaka": "감바 오사카", "Kashima Antlers": "가시마 앤틀러스",
    "Urawa Red Diamonds": "우라와 레즈", "Kawasaki Frontale": "가와사키 프론탈레", "Yokohama F. Marinos": "요코하마 F. 마리노스",
    "FC Tokyo": "FC 도쿄", "Sanfrecce Hiroshima": "산프레체 히로시마", "Nagoya Grampus": "나고야 그램퍼스",
    "Cerezo Osaka": "세레소 오사카", "Kashiwa Reysol": "가시와 레이솔", "Machida Zelvia": "마치다 젤비아",
    "FC Machida Zelvia": "마치다 젤비아", "Tokyo Verdy": "도쿄 베르디", "Albirex Niigata": "알비렉스 니가타",
    "Shonan Bellmare": "쇼난 벨마레", "Avispa Fukuoka": "아비스파 후쿠오카", "Hokkaido Consadole Sapporo": "콘사도레 삿포로",
    "Kyoto Sanga": "교토 상가", "Jubilo Iwata": "주빌로 이와타", "Sagan Tosu": "사간 도스", "Shimizu S-Pulse": "시미즈 S펄스",
    "Fagiano Okayama": "파지아노 오카야마", "Yokohama FC": "요코하마 FC",
    "Kyoto Sanga FC": "교토 상가", "Consadole Sapporo": "콘사도레 삿포로", "Urawa Reds": "우라와 레즈",
    # J2·J3 (일왕배에 자주 나옴)
    "Tokushima Vortis": "도쿠시마 보르티스", "Ventforet Kofu": "반포레 고후", "FC Imabari": "FC 이마바리",
    "Fujieda MYFC": "후지에다 MYFC", "Tochigi City FC": "도치기 시티", "Tochigi City": "도치기 시티", "Tochigi SC": "도치기 SC",
    "V-Varen Nagasaki": "V바렌 나가사키", "JEF United Chiba": "JEF 유나이티드 지바", "JEF United": "JEF 유나이티드 지바",
    "Vegalta Sendai": "베갈타 센다이", "Montedio Yamagata": "몬테디오 야마가타", "Oita Trinita": "오이타 트리니타",
    "Roasso Kumamoto": "로아소 구마모토", "Blaublitz Akita": "블라우블리츠 아키타", "Iwaki FC": "이와키 FC",
    "Mito HollyHock": "미토 홀리호크", "Mito Hollyhock": "미토 홀리호크", "Renofa Yamaguchi": "레노파 야마구치",
    "Ehime FC": "에히메 FC", "Kataller Toyama": "카탈레 도야마", "Zweigen Kanazawa": "츠바이겐 가나자와",
    "Thespa Gunma": "테스파 군마", "Thespakusatsu Gunma": "테스파 군마", "Kagoshima United": "가고시마 유나이티드",
    "Omiya Ardija": "오미야 아르디자", "RB Omiya Ardija": "RB 오미야 아르디자", "Giravanz Kitakyushu": "기라반츠 기타큐슈",
    "Tokushima": "도쿠시마 보르티스", "FC Gifu": "FC 기후", "Matsumoto Yamaga": "마쓰모토 야마가", "Nagano Parceiro": "나가노 파르세이로",
    "Kamatamare Sanuki": "가마타마레 사누키", "FC Ryukyu": "FC 류큐", "Azul Claro Numazu": "아술 클라로 누마즈",
    "Gainare Tottori": "가이나레 돗토리", "SC Sagamihara": "SC 사가미하라", "Iwate Grulla Morioka": "이와테 그루자 모리오카",
    "Vanraure Hachinohe": "반라우레 하치노헤", "FC Osaka": "FC 오사카", "Nara Club": "나라 클럽", "Kochi United": "고치 유나이티드",
    "Tegevajaro Miyazaki": "테게바자로 미야자키", "Tegevajaro": "테게바자로 미야자키",
    "Ryukyu": "FC 류큐", "Grulla Morioka": "이와테 그루자 모리오카", "Fukushima United": "후쿠시마 유나이티드",
    "Tottori": "가이나레 돗토리", "Sagamihara": "SC 사가미하라", "Imabari": "FC 이마바리",
    # MLS (2026년 30개 구단) — ESPN 표기와 줄임말을 같이 넣는다
    "Inter Miami CF": "인터 마이애미", "Inter Miami": "인터 마이애미",
    "LA Galaxy": "LA 갤럭시", "Los Angeles Galaxy": "LA 갤럭시",
    "Los Angeles FC": "LAFC", "LAFC": "LAFC",
    "Seattle Sounders FC": "시애틀 사운더스", "Seattle Sounders": "시애틀 사운더스",
    "Atlanta United FC": "애틀랜타 유나이티드", "Atlanta United": "애틀랜타 유나이티드",
    "New York City FC": "뉴욕 시티", "NYCFC": "뉴욕 시티",
    "New York Red Bulls": "뉴욕 레드불스", "NY Red Bulls": "뉴욕 레드불스", "Red Bull New York": "뉴욕 레드불스",
    "Portland Timbers": "포틀랜드 팀버스",
    "Columbus Crew": "컬럼버스 크루", "Columbus Crew SC": "컬럼버스 크루",
    "FC Cincinnati": "FC 신시내티",
    "Philadelphia Union": "필라델피아 유니온",
    "Toronto FC": "토론토 FC",
    "Vancouver Whitecaps FC": "밴쿠버 화이트캡스", "Vancouver Whitecaps": "밴쿠버 화이트캡스",
    "CF Montreal": "CF 몬트리올", "CF Montréal": "CF 몬트리올", "Montreal Impact": "CF 몬트리올",
    "Chicago Fire FC": "시카고 파이어", "Chicago Fire": "시카고 파이어",
    "Orlando City SC": "올랜도 시티", "Orlando City": "올랜도 시티",
    "Nashville SC": "내슈빌 SC",
    "Austin FC": "오스틴 FC",
    "St. Louis City SC": "세인트루이스 시티", "St Louis City SC": "세인트루이스 시티", "St. Louis CITY SC": "세인트루이스 시티",
    "Charlotte FC": "샬럿 FC",
    "FC Dallas": "FC 댈러스",
    "Houston Dynamo FC": "휴스턴 다이너모", "Houston Dynamo": "휴스턴 다이너모",
    "Sporting Kansas City": "스포팅 캔자스시티", "Sporting KC": "스포팅 캔자스시티",
    "Minnesota United FC": "미네소타 유나이티드", "Minnesota United": "미네소타 유나이티드",
    "Colorado Rapids": "콜로라도 래피즈",
    "Real Salt Lake": "리얼 솔트레이크",
    "San Jose Earthquakes": "산호세 어스퀘이크스",
    "D.C. United": "D.C. 유나이티드", "DC United": "D.C. 유나이티드",
    "New England Revolution": "뉴잉글랜드 레볼루션",
    "San Diego FC": "샌디에이고 FC",
    # MLS 하위/컵대회에서 가끔 올라오는 팀
    "Colorado Rapids 2": "콜로라도 래피즈 2", "New York Red Bulls II": "뉴욕 레드불스 2",
    "Orange County SC": "오렌지 카운티 SC", "Sacramento Republic FC": "새크라멘토 리퍼블릭",
    "Phoenix Rising FC": "피닉스 라이징", "Louisville City FC": "루이빌 시티",
    "Indy Eleven": "인디 일레븐", "Tampa Bay Rowdies": "탬파베이 라우디스",
    "Detroit City FC": "디트로이트 시티", "El Paso Locomotive FC": "엘패소 로코모티브",
}

NATIONS = {
    # 아시아·오세아니아
    "South Korea": "대한민국", "Korea Republic": "대한민국", "Japan": "일본", "China": "중국", "China PR": "중국",
    "Australia": "호주", "Iran": "이란", "IR Iran": "이란", "Saudi Arabia": "사우디아라비아", "Qatar": "카타르",
    "Iraq": "이라크", "United Arab Emirates": "아랍에미리트", "UAE": "아랍에미리트", "Uzbekistan": "우즈베키스탄",
    "Jordan": "요르단", "Oman": "오만", "Bahrain": "바레인", "Kuwait": "쿠웨이트", "Syria": "시리아", "Lebanon": "레바논",
    "Palestine": "팔레스타인", "Thailand": "태국", "Vietnam": "베트남", "Indonesia": "인도네시아", "Malaysia": "말레이시아",
    "Philippines": "필리핀", "Singapore": "싱가포르", "India": "인도", "Kyrgyzstan": "키르기스스탄", "Tajikistan": "타지키스탄",
    "North Korea": "북한", "Korea DPR": "북한", "Hong Kong": "홍콩", "Chinese Taipei": "대만", "New Zealand": "뉴질랜드",
    "Fiji": "피지", "Vanuatu": "바누아투", "New Caledonia": "뉴칼레도니아", "Solomon Islands": "솔로몬 제도",
    "Papua New Guinea": "파푸아뉴기니", "Tahiti": "타히티", "Turkmenistan": "투르크메니스탄", "Myanmar": "미얀마",
    # 유럽
    "England": "잉글랜드", "France": "프랑스", "Germany": "독일", "Spain": "스페인", "Italy": "이탈리아",
    "Portugal": "포르투갈", "Netherlands": "네덜란드", "Belgium": "벨기에", "Croatia": "크로아티아",
    "Switzerland": "스위스", "Denmark": "덴마크", "Sweden": "스웨덴", "Norway": "노르웨이", "Poland": "폴란드",
    "Austria": "오스트리아", "Czechia": "체코", "Czech Republic": "체코", "Serbia": "세르비아", "Scotland": "스코틀랜드",
    "Wales": "웨일스", "Republic of Ireland": "아일랜드", "Ireland": "아일랜드", "Northern Ireland": "북아일랜드",
    "Ukraine": "우크라이나", "Turkey": "튀르키예", "Turkiye": "튀르키예", "Greece": "그리스", "Hungary": "헝가리",
    "Romania": "루마니아", "Slovakia": "슬로바키아", "Slovenia": "슬로베니아", "Finland": "핀란드", "Iceland": "아이슬란드",
    "Albania": "알바니아", "Georgia": "조지아", "Bosnia and Herzegovina": "보스니아 헤르체고비나",
    "Bosnia-Herzegovina": "보스니아 헤르체고비나", "North Macedonia": "북마케도니아", "Montenegro": "몬테네그로",
    "Kosovo": "코소보", "Israel": "이스라엘", "Bulgaria": "불가리아", "Belarus": "벨라루스", "Lithuania": "리투아니아",
    "Latvia": "라트비아", "Estonia": "에스토니아", "Azerbaijan": "아제르바이잔", "Armenia": "아르메니아",
    "Kazakhstan": "카자흐스탄", "Luxembourg": "룩셈부르크", "Cyprus": "키프로스", "Malta": "몰타", "Moldova": "몰도바",
    "Faroe Islands": "페로 제도", "Andorra": "안도라", "San Marino": "산마리노", "Liechtenstein": "리히텐슈타인",
    "Gibraltar": "지브롤터", "Russia": "러시아",
    # 아메리카
    "Argentina": "아르헨티나", "Brazil": "브라질", "Uruguay": "우루과이", "Colombia": "콜롬비아", "Ecuador": "에콰도르",
    "Chile": "칠레", "Peru": "페루", "Paraguay": "파라과이", "Venezuela": "베네수엘라", "Bolivia": "볼리비아",
    "United States": "미국", "USA": "미국", "Mexico": "멕시코", "Canada": "캐나다", "Costa Rica": "코스타리카",
    "Panama": "파나마", "Jamaica": "자메이카", "Honduras": "온두라스", "El Salvador": "엘살바도르", "Guatemala": "과테말라",
    "Haiti": "아이티", "Trinidad and Tobago": "트리니다드 토바고", "Curacao": "퀴라소", "Dominica": "도미니카 연방",
    "Dominican Republic": "도미니카 공화국", "Anguilla": "앵귈라", "Cuba": "쿠바", "Nicaragua": "니카라과",
    "Suriname": "수리남", "Guyana": "가이아나", "Bermuda": "버뮤다", "Puerto Rico": "푸에르토리코",
    # 아프리카
    "Morocco": "모로코", "Senegal": "세네갈", "Egypt": "이집트", "Nigeria": "나이지리아", "Ghana": "가나",
    "Cameroon": "카메룬", "Ivory Coast": "코트디부아르", "Cote d'Ivoire": "코트디부아르", "Algeria": "알제리",
    "Tunisia": "튀니지", "South Africa": "남아프리카 공화국", "Mali": "말리", "Burkina Faso": "부르키나파소",
    "DR Congo": "콩고민주공화국", "Congo DR": "콩고민주공화국", "Cape Verde": "카보베르데", "Cabo Verde": "카보베르데",
    "Guinea": "기니", "Zambia": "잠비아", "Angola": "앙골라", "Gabon": "가봉", "Uganda": "우간다", "Kenya": "케냐",
    "Benin": "베냉", "Libya": "리비아", "Equatorial Guinea": "적도기니", "Mozambique": "모잠비크", "Tanzania": "탄자니아",
    "Zimbabwe": "짐바브웨", "Sudan": "수단", "Namibia": "나미비아", "Madagascar": "마다가스카르",
}


def _key(name):
    t = unicodedata.normalize("NFKD", str(name or "")).encode("ascii", "ignore").decode("ascii").lower()
    t = t.replace("&", " and ").replace("'", "")
    t = re.sub(r"[^a-z0-9 ]+", " ", t)
    return re.sub(r"\s+", " ", t).strip()


_TABLE = {}
for _src in (MLB, CLUBS, NATIONS):
    for _en, _ko in _src.items():
        _TABLE.setdefault(_key(_en), _ko)

# ---------------------------------------------------------------- 2026-09 추가: 새로 넣은 대회들의 팀·나라
NATIONS.update({
    "Sao Tome and Principe": "상투메 프린시페", "São Tomé and Príncipe": "상투메 프린시페", "Cape Verde": "카보베르데",
    "Guinea-Bissau": "기니비사우", "Equatorial Guinea": "적도 기니", "Central African Republic": "중앙아프리카공화국",
    "Congo DR": "콩고민주공화국", "DR Congo": "콩고민주공화국", "Congo": "콩고", "Eswatini": "에스와티니", "Lesotho": "레소토",
    "Comoros": "코모로", "Djibouti": "지부티", "Eritrea": "에리트레아", "Seychelles": "세이셸", "Mauritius": "모리셔스",
    "Madagascar": "마다가스카르", "Malawi": "말라위", "Botswana": "보츠와나", "Namibia": "나미비아", "Zimbabwe": "짐바브웨",
    "Mozambique": "모잠비크", "Angola": "앙골라", "Gambia": "감비아", "Sierra Leone": "시에라리온", "Liberia": "라이베리아",
    "Togo": "토고", "Benin": "베냉", "Niger": "니제르", "Chad": "차드", "Sudan": "수단", "South Sudan": "남수단",
    "Somalia": "소말리아", "Mauritania": "모리타니", "Burundi": "부룬디", "Rwanda": "르완다", "Uganda": "우간다",
    "Tanzania": "탄자니아", "Zambia": "잠비아", "Gabon": "가봉", "Guinea": "기니",
    "Palestine": "팔레스타인", "Yemen": "예멘", "Bahrain": "바레인", "Kuwait": "쿠웨이트", "Oman": "오만",
    "Turkmenistan": "투르크메니스탄", "Kyrgyzstan": "키르기스스탄", "Afghanistan": "아프가니스탄", "Maldives": "몰디브",
    "Nepal": "네팔", "Bhutan": "부탄", "Bangladesh": "방글라데시", "Sri Lanka": "스리랑카", "Myanmar": "미얀마",
    "Laos": "라오스", "Cambodia": "캄보디아", "Brunei": "브루나이", "Timor-Leste": "동티모르", "Macau": "마카오",
    "Mongolia": "몽골", "Chinese Taipei": "대만", "Guam": "괌", "Northern Mariana Islands": "북마리아나제도",
    "Papua New Guinea": "파푸아뉴기니", "Vanuatu": "바누아투", "New Caledonia": "뉴칼레도니아", "Solomon Islands": "솔로몬 제도",
    "Fiji": "피지", "Tahiti": "타히티", "Samoa": "사모아", "American Samoa": "아메리칸사모아", "Tonga": "통가",
    "Cook Islands": "쿡 제도", "Trinidad and Tobago": "트리니다드 토바고", "Suriname": "수리남", "Guyana": "가이아나",
    "Curacao": "퀴라소", "Curaçao": "퀴라소", "Aruba": "아루바", "Barbados": "바베이도스", "Grenada": "그레나다",
    "Saint Lucia": "세인트루시아", "Saint Kitts and Nevis": "세인트키츠 네비스", "Antigua and Barbuda": "앤티가 바부다",
    "Dominican Republic": "도미니카공화국", "Dominica": "도미니카 연방", "Haiti": "아이티", "Nicaragua": "니카라과",
    "Belize": "벨리즈", "Cayman Islands": "케이맨 제도", "Bermuda": "버뮤다", "Bahamas": "바하마", "Puerto Rico": "푸에르토리코",
    "Montserrat": "몬트세랫", "Anguilla": "앵귈라", "British Virgin Islands": "영국령 버진아일랜드",
    "US Virgin Islands": "미국령 버진아일랜드", "Turks and Caicos Islands": "터크스 케이커스 제도",
    "Saint Vincent and the Grenadines": "세인트빈센트 그레나딘", "San Marino": "산마리노", "Liechtenstein": "리히텐슈타인",
    "Andorra": "안도라", "Malta": "몰타", "Faroe Islands": "페로 제도", "Kosovo": "코소보", "Moldova": "몰도바",
    "St. Martin": "세인트마틴", "Saint Martin": "세인트마틴", "Sint Maarten": "신트마르턴", "Saint Barthelemy": "생바르텔레미", "Guadeloupe": "과들루프", "Martinique": "마르티니크", "French Guiana": "프랑스령 기아나", "Bonaire": "보네르", "Ivory Coast": "코트디부아르", "Cote d'Ivoire": "코트디부아르", "Congo-Brazzaville": "콩고", "Swaziland": "에스와티니", "North Macedonia": "북마케도니아", "Macedonia": "북마케도니아", "Bosnia and Herzegovina": "보스니아 헤르체고비나", "Bosnia & Herzegovina": "보스니아 헤르체고비나", "Trinidad & Tobago": "트리니다드 토바고", "Antigua & Barbuda": "앤티가 바부다", "St. Kitts & Nevis": "세인트키츠 네비스", "St. Vincent & Grenadines": "세인트빈센트 그레나딘", "Turks & Caicos Islands": "터크스 케이커스 제도", "British Virgin Isles": "영국령 버진아일랜드", "US Virgin Isles": "미국령 버진아일랜드", "Sao Tome & Principe": "상투메 프린시페", "Cabo Verde": "카보베르데",
})

CLUBS.update({
    # 사우디
    "Al Hilal": "알 힐랄", "Al Nassr": "알 나스르", "Al Ittihad": "알 이티하드", "Al Ahli": "알 아흘리", "Al Shabab": "알 샤밥",
    "Al Ettifaq": "알 이티파크", "Al Taawoun": "알 타아운", "Al Fateh": "알 파테흐", "Al Fayha": "알 파이하", "Al Khaleej": "알 칼리지",
    "Al Riyadh": "알 리야드", "Damac": "다막", "Al Wehda": "알 웨흐다", "Al Okhdood": "알 우크두드", "Al Raed": "알 라에드",
    "Al Qadsiah": "알 카디시야", "Al Najma": "알 나즈마", "Neom SC": "네옴", "Al Kholood": "알 쿨루드",
    # 중국
    "Shanghai Port": "상하이 포트", "Shanghai Shenhua": "상하이 선화", "Beijing Guoan": "베이징 궈안", "Shandong Taishan": "산둥 타이산",
    "Chengdu Rongcheng": "청두 룽청", "Zhejiang": "저장", "Wuhan Three Towns": "우한 싼전", "Tianjin Jinmen Tiger": "톈진 진먼 타이거",
    "Henan": "허난", "Changchun Yatai": "창춘 야타이", "Meizhou Hakka": "메이저우 하카", "Qingdao West Coast": "칭다오 웨스트코스트",
    "Yunnan Yukun": "윈난 위쿤", "Qingdao Hainiu": "칭다오 하이뉴", "Dalian Yingbo": "다롄 잉보", "Shenzhen Peng City": "선전 펑시티",
    # 호주
    "Melbourne Victory": "멜버른 빅토리", "Melbourne City": "멜버른 시티", "Sydney FC": "시드니 FC",
    "Western Sydney Wanderers": "웨스턴 시드니", "Adelaide United": "애들레이드 유나이티드", "Brisbane Roar": "브리즈번 로어",
    "Central Coast Mariners": "센트럴코스트 마리너스", "Perth Glory": "퍼스 글로리", "Wellington Phoenix": "웰링턴 피닉스",
    "Macarthur FC": "맥아더", "Newcastle Jets": "뉴캐슬 제츠", "Western United": "웨스턴 유나이티드", "Auckland FC": "오클랜드 FC",
    # 멕시코
    "Club America": "클럽 아메리카", "América": "클럽 아메리카", "Guadalajara Chivas": "과달라하라", "Chivas Guadalajara": "과달라하라",
    "Cruz Azul": "크루스 아술", "Pumas UNAM": "푸마스 UNAM", "UNAM": "푸마스 UNAM", "Tigres UANL": "티그레스",
    "Monterrey": "몬테레이", "Toluca": "톨루카", "Santos Laguna": "산토스 라구나", "Leon": "레온", "León": "레온",
    "Pachuca": "파추카", "Necaxa": "네카사", "Atlas": "아틀라스", "Puebla": "푸에블라", "Tijuana": "티후아나",
    "Juarez": "후아레스", "Queretaro": "케레타로", "Mazatlan": "마사틀란", "Atletico San Luis": "산루이스",
    # 브라질
    "Flamengo": "플라멩구", "Palmeiras": "팔메이라스", "Corinthians": "코린치안스", "Sao Paulo": "상파울루", "Santos": "산투스",
    "Gremio": "그레미우", "Internacional": "인테르나시오나우", "Cruzeiro": "크루제이루", "Atletico Mineiro": "아틀레치쿠 미네이루",
    "Botafogo": "보타포구", "Fluminense": "플루미넨시", "Vasco da Gama": "바스쿠 다 가마", "Bahia": "바이아", "Fortaleza": "포르탈레자",
    "Red Bull Bragantino": "브라간치누", "Juventude": "주벤투지", "Ceara": "세아라", "Vitoria": "비토리아", "Mirassol": "미라솔",
    "Sport Recife": "스포르트 헤시피", "Athletico Paranaense": "아틀레치쿠 파라나엔시", "Coritiba": "코리치바", "Goias": "고이아스",
    "Chapecoense": "샤페코엔시", "Novorizontino": "노보리존치누", "Remo": "레무", "Avai": "아바이",
    # 아르헨티나
    "Boca Juniors": "보카 주니어스", "River Plate": "리버 플레이트", "Racing Club": "라싱 클루브", "Independiente": "인데펜디엔테",
    "San Lorenzo": "산 로렌소", "Estudiantes": "에스투디안테스", "Velez Sarsfield": "벨레스 사르스필드",
    "Newell's Old Boys": "뉴웰스 올드 보이스", "Rosario Central": "로사리오 센트랄", "Talleres": "탈레레스", "Lanus": "라누스",
    "Argentinos Juniors": "아르헨티노스 주니어스", "Defensa y Justicia": "데펜사 이 후스티시아", "Huracan": "우라칸",
    "Banfield": "반필드", "Godoy Cruz": "고도이 크루스", "Instituto": "인스티투토", "Platense": "플라텐세", "Tigre": "티그레",
    "Belgrano": "벨그라노", "Gimnasia La Plata": "힘나시아", "Barracas Central": "바라카스 센트랄", "Central Cordoba": "센트랄 코르도바",
    # 콜롬비아·칠레·페루·우루과이·에콰도르
    "Atletico Nacional": "아틀레티코 나시오날", "Millonarios": "미요나리오스", "America de Cali": "아메리카 데 칼리",
    "Deportivo Cali": "데포르티보 칼리", "Junior": "후니오르", "Independiente Santa Fe": "산타페", "Once Caldas": "온세 칼다스",
    "Deportes Tolima": "톨리마", "Independiente Medellin": "메데인", "Atletico Bucaramanga": "부카라망가",
    "Colo Colo": "콜로콜로", "Universidad de Chile": "우니베르시다드 데 칠레", "Universidad Catolica": "우니베르시다드 카톨리카",
    "Palestino": "팔레스티노", "Cobresal": "코브레살", "Huachipato": "우아치파토", "Audax Italiano": "아우닥스 이탈리아노",
    "Everton de Vina": "에베르톤", "Universitario": "우니베르시타리오", "Alianza Lima": "알리안사 리마",
    "Sporting Cristal": "스포르팅 크리스탈", "Melgar": "멜가르", "Cienciano": "시엔시아노",
    "Penarol": "페냐롤", "Nacional": "나시오날", "Defensor Sporting": "데펜소르", "Liverpool Montevideo": "리베르풀 몬테비데오",
    "Barcelona SC": "바르셀로나 SC", "LDU Quito": "LDU 키토", "Independiente del Valle": "인데펜디엔테 델 바예",
    "Emelec": "에멜렉", "Aucas": "아우카스",
    # 스코틀랜드·벨기에·오스트리아
    "Hearts": "하츠", "Heart of Midlothian": "하츠", "Hibernian": "히버니언", "Aberdeen": "애버딘", "Dundee United": "던디 유나이티드",
    "Motherwell": "머더웰", "St Mirren": "세인트 미렌", "Kilmarnock": "킬마녹", "Dundee": "던디", "Ross County": "로스 카운티",
    "St Johnstone": "세인트 존스턴", "Falkirk": "폴커크", "Livingston": "리빙스턴",
    "Anderlecht": "안더레흐트", "Genk": "헹크", "Standard Liege": "스탕다르 리에주", "Gent": "헨트", "Antwerp": "안트베르펜",
    "Union Saint-Gilloise": "위니옹 생질루아즈", "Charleroi": "샤를루아", "Cercle Brugge": "세르클러 브뤼허", "Mechelen": "메헬렌",
    "Westerlo": "베스테를로", "OH Leuven": "OH 뢰번", "Sint-Truiden": "신트트라위던", "Dender": "덴더", "Zulte Waregem": "쥘터 바레험",
    "Red Bull Salzburg": "레드불 잘츠부르크", "Rapid Vienna": "라피트 빈", "Austria Vienna": "아우스트리아 빈", "Sturm Graz": "슈투름 그라츠",
    "LASK": "LASK", "Wolfsberger AC": "볼프스베르거", "TSV Hartberg": "하르트베르크", "Blau-Weiss Linz": "블라우바이스 린츠",
    "SCR Altach": "알타흐", "Austria Klagenfurt": "아우스트리아 클라겐푸르트", "Grazer AK": "그라처 AK", "SV Ried": "리트",
    # 북유럽·그리스·러시아
    "FC Copenhagen": "코펜하겐", "Midtjylland": "미트윌란", "Brondby": "브뢰네뷔", "AGF": "AGF", "Silkeborg": "실케보르",
    "Nordsjaelland": "노르셸란", "Randers": "란데르스", "Viborg": "비보르", "Lyngby": "륑뷔", "Vejle": "바일레",
    "AaB": "올보르", "Sonderjyske": "쇤데르위스케", "Fredericia": "프레데리시아",
    "Bodo/Glimt": "보되/글림트", "Molde": "몰데", "Rosenborg": "로센보르그", "Brann": "브란", "Viking": "비킹",
    "Lillestrom": "릴레스트룀", "Valerenga": "발레렝가", "Tromso": "트롬쇠", "Sarpsborg 08": "사르프스보르", "Haugesund": "헤우게순",
    "Fredrikstad": "프레드릭스타드", "KFUM Oslo": "KFUM 오슬로", "Sandefjord": "산데피오르", "Stromsgodset": "스트룀스고드세트",
    "Kristiansund": "크리스티안순", "Bryne": "브리네",
    "Malmo FF": "말뫼", "AIK": "AIK", "Djurgarden": "유르고덴", "Hammarby": "함마르뷔", "IFK Goteborg": "예테보리",
    "Elfsborg": "엘프스보리", "Hacken": "헤켄", "Norrkoping": "노르셰핑", "Mjallby": "미엘뷔", "Sirius": "시리우스",
    "Varnamo": "베르나모", "Brommapojkarna": "브롬마포이카르나", "Degerfors": "데예르포르스", "Halmstad": "할름스타드",
    "GAIS": "GAIS", "Osters": "외스테르스",
    "Olympiacos": "올림피아코스", "Panathinaikos": "파나티나이코스", "AEK Athens": "AEK 아테네", "PAOK": "PAOK",
    "Aris": "아리스", "OFI Crete": "OFI", "Volos": "볼로스", "Atromitos": "아트로미토스", "Panetolikos": "파네톨리코스",
    "Levadiakos": "레바디아코스", "Asteras Tripolis": "아스테라스 트리폴리스", "Kifisia": "키피시아",
    "Zenit St Petersburg": "제니트", "Spartak Moscow": "스파르타크 모스크바", "CSKA Moscow": "CSKA 모스크바",
    "Lokomotiv Moscow": "로코모티프 모스크바", "Dynamo Moscow": "디나모 모스크바", "Krasnodar": "크라스노다르",
    "Rubin Kazan": "루빈 카잔", "Rostov": "로스토프", "Akhmat Grozny": "아흐마트 그로즈니", "Krylia Sovetov": "크릴리야 소베토프",
    "Akron Togliatti": "아크론", "Dynamo Makhachkala": "디나모 마하치칼라", "Orenburg": "오렌부르크", "Baltika": "발티카",
    "Pari Nizhny Novgorod": "파리 NN", "Sochi": "소치",
    # 인도
    "Mohun Bagan": "모훈 바간", "East Bengal": "이스트 벵골", "Bengaluru FC": "벵갈루루", "Mumbai City": "뭄바이 시티",
    "FC Goa": "고아", "Kerala Blasters": "케랄라 블래스터스", "Odisha FC": "오디샤", "Jamshedpur": "잠셰드푸르",
    "Chennaiyin": "첸나이인", "NorthEast United": "노스이스트 유나이티드", "Punjab FC": "펀자브", "Hyderabad FC": "하이데라바드",
    # 독일2·이탈리아2·프랑스2·네덜란드2 (자주 나오는 팀)
    "Schalke 04": "샬케 04", "Hertha Berlin": "헤르타 베를린", "Fortuna Dusseldorf": "포르투나 뒤셀도르프",
    "Karlsruher SC": "카를스루에", "Hannover 96": "하노버 96", "Nurnberg": "뉘른베르크", "Paderborn": "파더보른",
    "Magdeburg": "마그데부르크", "Kaiserslautern": "카이저슬라우테른", "Darmstadt": "다름슈타트", "Greuther Furth": "그로이터 퓌르트",
    "Elversberg": "엘버스베르크", "Eintracht Braunschweig": "브라운슈바이크", "Preussen Munster": "프로이센 뮌스터",
    "Arminia Bielefeld": "아르미니아 빌레펠트", "Dynamo Dresden": "디나모 드레스덴", "Bochum": "보훔",
    "Palermo": "팔레르모", "Sampdoria": "삼프도리아", "Venezia": "베네치아", "Monza": "몬차", "Empoli": "엠폴리",
    "Spezia": "스페치아", "Frosinone": "프로시노네", "Bari": "바리", "Catanzaro": "카탄차로", "Cesena": "체세나",
    "Modena": "모데나", "Reggiana": "레지아나", "Sudtirol": "쉬트티롤", "Juve Stabia": "유베 스타비아", "Avellino": "아벨리노",
    "Pescara": "페스카라", "Mantova": "만토바", "Padova": "파도바", "Virtus Entella": "엔텔라", "Carrarese": "카라레세",
    "Troyes": "트루아", "Guingamp": "갱강", "Amiens": "아미앵", "Bastia": "바스티아", "Clermont Foot": "클레르몽",
    "Dunkerque": "덩케르크", "Grenoble": "그르노블", "Laval": "라발", "Le Mans": "르망", "Montpellier": "몽펠리에",
    "Pau FC": "포", "Red Star FC": "레드스타", "Rodez": "로데즈", "Annecy": "안시", "Boulogne": "불로뉴",
    "FC Eindhoven": "에인트호번 FC", "De Graafschap": "더 그라프스합", "Cambuur": "캄뷔르", "Roda JC": "로다 JC",
    "Emmen": "엠멘", "VVV-Venlo": "VVV 펜로", "Den Bosch": "덴 보스", "Dordrecht": "도르드레흐트", "Helmond Sport": "헬몬트",
    "MVV Maastricht": "MVV", "TOP Oss": "TOP 오스", "Jong Ajax": "융 아약스", "Jong PSV": "융 PSV", "Jong AZ": "융 AZ",
    "Jong Utrecht": "융 위트레흐트", "Willem II": "빌럼 II", "Telstar": "텔스타르", "Volendam": "폴렌담",
})

for _src in (CLUBS, NATIONS):                       # 새로 넣은 이름도 찾을 수 있게 다시 만든다
    for _en, _ko in _src.items():
        _TABLE.setdefault(_key(_en), _ko)

_WOMEN = re.compile(r"\s*(women|womens|w)$")


def ko_team(name):
    """영어 팀 이름 -> 한국어 (사전에 없으면 원래 이름)."""
    raw = str(name or "")
    if not raw or re.search(r"[가-힣]", raw):
        return raw                                   # 이미 한국어(네이버 등)
    k = _key(raw)
    if k in _TABLE:
        return _TABLE[k]
    m = _WOMEN.search(k)
    if m:                                            # 여자 대표팀: "South Korea Women" -> "대한민국 여자"
        base = k[:m.start()].strip()
        if base in _TABLE:
            return _TABLE[base] + " 여자"
    return raw

# ---------------------------------------------------------------- 선수 이름 (직접 채운 사전)
PLAYERS = {
    "Erling Haaland": "엘링 홀란",
    "Rodri": "로드리",
    "Phil Foden": "필 포든",
    "Bernardo Silva": "베르나르두 실바",
    "Ruben Dias": "후벵 디아스",
    "Josko Gvardiol": "요슈코 그바르디올",
    "Ederson": "에데르송",
    "Jeremy Doku": "제레미 도쿠",
    "Savinho": "사비뉴",
    "Mateo Kovacic": "마테오 코바치치",
    "Nathan Ake": "네이선 아케",
    "John Stones": "존 스톤스",
    "Kyle Walker": "카일 워커",
    "Matheus Nunes": "마테우스 누느스",
    "Ilkay Gundogan": "일카이 귄도안",
    "Omar Marmoush": "오마르 마르무시",
    "Bukayo Saka": "부카요 사카",
    "Martin Odegaard": "마르틴 외데고르",
    "Declan Rice": "데클란 라이스",
    "William Saliba": "윌리엄 살리바",
    "Gabriel Magalhaes": "가브리엘 마갈량이스",
    "Gabriel Martinelli": "가브리에우 마르티넬리",
    "Kai Havertz": "카이 하베르츠",
    "David Raya": "다비드 라야",
    "Ben White": "벤 화이트",
    "Leandro Trossard": "레안드로 트로사르",
    "Jurrien Timber": "유리엔 팀버",
    "Mikel Merino": "미켈 메리노",
    "Viktor Gyokeres": "빅토르 요케레스",
    "Martin Zubimendi": "마르틴 수비멘디",
    "Riccardo Calafiori": "리카르도 칼라피오리",
    "Mohamed Salah": "모하메드 살라",
    "Virgil van Dijk": "버질 반다이크",
    "Alisson": "알리송",
    "Ryan Gravenberch": "라이언 흐라번베르흐",
    "Dominik Szoboszlai": "도미니크 소보슬러이",
    "Luis Diaz": "루이스 디아스",
    "Cody Gakpo": "코디 학포",
    "Ibrahima Konate": "이브라히마 코나테",
    "Andrew Robertson": "앤드루 로버트슨",
    "Trent Alexander-Arnold": "트렌트 알렉산더아널드",
    "Curtis Jones": "커티스 존스",
    "Alexis Mac Allister": "알렉시스 맥알리스터",
    "Darwin Nunez": "다르윈 누녜스",
    "Florian Wirtz": "플로리안 비르츠",
    "Hugo Ekitike": "위고 에키티케",
    "Milos Kerkez": "밀로시 케르케즈",
    "Jeremie Frimpong": "예레미 프림퐁",
    "Cole Palmer": "콜 파머",
    "Enzo Fernandez": "엔소 페르난데스",
    "Moises Caicedo": "모이세스 카이세도",
    "Nicolas Jackson": "니콜라 잭슨",
    "Reece James": "리스 제임스",
    "Levi Colwill": "레비 콜윌",
    "Robert Sanchez": "로베르트 산체스",
    "Pedro Neto": "페드로 네투",
    "Joao Pedro": "주앙 페드루",
    "Liam Delap": "리암 딜랩",
    "Son Heung-Min": "손흥민",
    "James Maddison": "제임스 매디슨",
    "Dejan Kulusevski": "데얀 쿨루셉스키",
    "Cristian Romero": "크리스티안 로메로",
    "Micky van de Ven": "미키 판더펜",
    "Guglielmo Vicario": "굴리엘모 비카리오",
    "Brennan Johnson": "브레넌 존슨",
    "Bruno Fernandes": "브루누 페르난드스",
    "Marcus Rashford": "마커스 래시퍼드",
    "Kobbie Mainoo": "코비 마이누",
    "Lisandro Martinez": "리산드로 마르티네스",
    "Matthijs de Ligt": "마테이스 더리흐트",
    "Andre Onana": "안드레 오나나",
    "Amad Diallo": "아마드 디알로",
    "Alexander Isak": "알렉산더 이삭",
    "Bruno Guimaraes": "브루누 기마랑이스",
    "Anthony Gordon": "앤서니 고든",
    "Sandro Tonali": "산드로 토날리",
    "Nick Pope": "닉 포프",
    "Ollie Watkins": "올리 왓킨스",
    "Morgan Rogers": "모건 로저스",
    "Emiliano Martinez": "에밀리아노 마르티네스",
    "Bryan Mbeumo": "브라이언 음뵈모",
    "Yoane Wissa": "요안 위사",
    "Matheus Cunha": "마테우스 쿠냐",
    "Jarrod Bowen": "제러드 보언",
    "Lucas Paqueta": "루카스 파케타",
    "Eberechi Eze": "에베레치 에제",
    "Jean-Philippe Mateta": "장필리프 마테타",
    "Marc Guehi": "마크 게히",
    "Antoine Semenyo": "앙투안 세메뇨",
    "Dominic Solanke": "도미닉 솔란케",
    "Evanilson": "에바닐송",
    "Iliman Ndiaye": "일리망 은디아예",
    "Jordan Pickford": "조던 픽퍼드",
    "Kylian Mbappe": "킬리안 음바페",
    "Jude Bellingham": "주드 벨링엄",
    "Vinicius Junior": "비니시우스 주니오르",
    "Rodrygo": "호드리구",
    "Federico Valverde": "페데리코 발베르데",
    "Aurelien Tchouameni": "오렐리앵 추아메니",
    "Eduardo Camavinga": "에두아르두 카마빙가",
    "Antonio Rudiger": "안토니오 뤼디거",
    "Thibaut Courtois": "티보 쿠르투아",
    "Dani Carvajal": "다니 카르바할",
    "Eder Militao": "에데르 밀리탕",
    "Arda Guler": "아르다 귈레르",
    "Dean Huijsen": "딘 하위선",
    "Trent Alexander Arnold": "트렌트 알렉산더아널드",
    "Brahim Diaz": "브라힘 디아스",
    "Fran Garcia": "프란 가르시아",
    "Lamine Yamal": "라민 야말",
    "Robert Lewandowski": "로베르트 레반도프스키",
    "Raphinha": "하피냐",
    "Pedri": "페드리",
    "Frenkie de Jong": "프렝키 더용",
    "Pau Cubarsi": "파우 쿠바르시",
    "Ronald Araujo": "로날드 아라우호",
    "Jules Kounde": "쥘 쿤데",
    "Gavi": "가비",
    "Ferran Torres": "페란 토레스",
    "Dani Olmo": "다니 올모",
    "Marc-Andre ter Stegen": "마르크안드레 테어슈테겐",
    "Marcus Rashford Barcelona": "마커스 래시퍼드",
    "Joan Garcia": "조안 가르시아",
    "Alejandro Balde": "알레한드로 발데",
    "Antoine Griezmann": "앙투안 그리즈만",
    "Julian Alvarez": "훌리안 알바레스",
    "Jan Oblak": "얀 오블락",
    "Koke": "코케",
    "Alexander Sorloth": "알렉산데르 쇠를로트",
    "Nahuel Molina": "나우엘 몰리나",
    "Jose Gimenez": "호세 히메네스",
    "Mikel Oyarzabal": "미켈 오야르사발",
    "Take Kubo": "구보 다케후사",
    "Alex Remiro": "알렉스 레미로",
    "Nico Williams": "니코 윌리엄스",
    "Inaki Williams": "이냐키 윌리엄스",
    "Oihan Sancet": "오이안 산세트",
    "Unai Simon": "우나이 시몬",
    "Isco": "이스코",
    "Antony": "안토니",
    "Giovani Lo Celso": "조바니 로셀소",
    "Borja Iglesias": "보르하 이글레시아스",
    "Ante Budimir": "안테 부디미르",
    "Kike Garcia": "키케 가르시아",
    "Iago Aspas": "이아고 아스파스",
    "Borja Mayoral": "보르하 마요랄",
    "Lautaro Martinez": "라우타로 마르티네스",
    "Marcus Thuram": "마르쿠스 튀랑",
    "Nicolo Barella": "니콜로 바렐라",
    "Hakan Calhanoglu": "하칸 찰하놀루",
    "Alessandro Bastoni": "알레산드로 바스토니",
    "Federico Dimarco": "페데리코 디마르코",
    "Yann Sommer": "얀 조머",
    "Rafael Leao": "하파엘 레앙",
    "Christian Pulisic": "크리스천 풀리식",
    "Mike Maignan": "마이크 메냥",
    "Theo Hernandez": "테오 에르난데스",
    "Fikayo Tomori": "피카요 토모리",
    "Tijjani Reijnders": "티자니 레이더르스",
    "Khvicha Kvaratskhelia": "흐비차 크바라츠헬리아",
    "Romelu Lukaku": "로멜루 루카쿠",
    "Alex Meret": "알렉스 메레트",
    "Giovanni Di Lorenzo": "조반니 디로렌초",
    "Scott McTominay": "스콧 맥토미니",
    "Kevin De Bruyne": "케빈 더브라위너",
    "Paulo Dybala": "파울로 디발라",
    "Artem Dovbyk": "아르템 도브비크",
    "Mile Svilar": "밀레 스빌라르",
    "Evan Ndicka": "에반 은디카",
    "Dusan Vlahovic": "두샨 블라호비치",
    "Kenan Yildiz": "케난 이을드즈",
    "Michele Di Gregorio": "미켈레 디그레고리오",
    "Manuel Locatelli": "마누엘 로카텔리",
    "Ademola Lookman": "아데몰라 루크먼",
    "Mateo Retegui": "마테오 레테기",
    "Charles De Ketelaere": "샤를 더케텔라러",
    "Moise Kean": "모이즈 킨",
    "Albert Gudmundsson": "알베르트 구드문손",
    "Victor Osimhen": "빅터 오시멘",
    "Nikola Krstovic": "니콜라 크르스토비치",
    "Harry Kane": "해리 케인",
    "Jamal Musiala": "자말 무시알라",
    "Michael Olise": "마이클 올리세",
    "Joshua Kimmich": "요주아 키미히",
    "Manuel Neuer": "마누엘 노이어",
    "Alphonso Davies": "알폰소 데이비스",
    "Dayot Upamecano": "다요 우파메카노",
    "Leon Goretzka": "레온 고레츠카",
    "Serge Gnabry": "세르주 그나브리",
    "Luis Diaz Bayern": "루이스 디아스",
    "Nick Woltemade": "닉 볼테마데",
    "Karim Adeyemi": "카림 아데예미",
    "Serhou Guirassy": "세루 기라시",
    "Julian Brandt": "율리안 브란트",
    "Gregor Kobel": "그레고어 코벨",
    "Pascal Gross": "파스칼 그로스",
    "Felix Nmecha": "펠릭스 은메차",
    "Florian Wirtz Leverkusen": "플로리안 비르츠",
    "Patrik Schick": "파트리크 시크",
    "Jonathan Tah": "요나탄 타",
    "Alejandro Grimaldo": "알레한드로 그리말도",
    "Victor Boniface": "빅터 보니페이스",
    "Jeremie Frimpong Leverkusen": "예레미 프림퐁",
    "Omar Marmoush Frankfurt": "오마르 마르무시",
    "Hugo Ekitike Frankfurt": "위고 에키티케",
    "Mario Gotze": "마리오 괴체",
    "Deniz Undav": "데니즈 운다프",
    "Angelo Stiller": "안젤로 슈틸러",
    "Ermedin Demirovic": "에르메딘 데미로비치",
    "Tim Kleindienst": "팀 클라인딘스트",
    "Jonas Hofmann": "요나스 호프만",
    "Loic Bade": "로이크 바데",
    "Ousmane Dembele": "우스만 뎀벨레",
    "Vitinha": "비치냐",
    "Achraf Hakimi": "아슈라프 하키미",
    "Marquinhos": "마르키뉴스",
    "Gianluigi Donnarumma": "잔루이지 돈나룸마",
    "Nuno Mendes": "누누 멘드스",
    "Joao Neves": "주앙 네베스",
    "Bradley Barcola": "브래들리 바르콜라",
    "Desire Doue": "데지레 두에",
    "Kvaratskhelia PSG": "흐비차 크바라츠헬리아",
    "Fabian Ruiz": "파비안 루이스",
    "Lucas Chevalier": "뤼카 슈발리에",
    "Mason Greenwood": "메이슨 그린우드",
    "Amine Gouiri": "아민 구이리",
    "Pierre-Emerick Aubameyang": "피에르에메릭 오바메양",
    "Adrien Rabiot": "아드리앵 라비오",
    "Jonathan David": "조너선 데이비드",
    "Georges Mikautadze": "조르주 미카우타제",
    "Arnaud Kalimuendo": "아르노 칼리무엔도",
    "Emanuel Emegha": "에마뉘엘 에메가",
    "Tyler Morton": "타일러 모턴",
    "Martin Satriano": "마르틴 사트리아노",
    "Alexandre Lacazette": "알렉상드르 라카제트",
    "Wesley Fofana": "웨슬리 포파나",
    "Viktor Gyokeres Sporting": "빅토르 요케레스",
    "Morten Hjulmand": "모르텐 율만",
    "Pedro Goncalves": "페드루 곤살베스",
    "Rafa Silva": "하파 실바",
    "Vangelis Pavlidis": "방겔리스 파블리디스",
    "Angel Di Maria": "앙헬 디마리아",
    "Samu Aghehowa": "사무 아게호와",
    "Pepe": "페페",
    "Diogo Costa": "디오구 코스타",
    "Luuk de Jong": "뤼크 더용",
    "Ivan Perisic": "이반 페리시치",
    "Noa Lang": "노아 랑",
    "Brian Brobbey": "브라이언 브로베이",
    "Steven Berghuis": "스테번 베르하위스",
    "Santiago Gimenez": "산티아고 히메네스",
    "Igor Paixao": "이고르 파이샹",
    "Cristiano Ronaldo": "크리스티아누 호날두",
    "Karim Benzema": "카림 벤제마",
    "Sadio Mane": "사디오 마네",
    "Riyad Mahrez": "리야드 마레즈",
    "Roberto Firmino": "호베르투 피르미누",
    "Aleksandar Mitrovic": "알렉산다르 미트로비치",
    "Ruben Neves": "후벵 네베스",
    "Malcom": "말콩",
    "Ivan Toney": "이반 토니",
    "Franck Kessie": "프랑크 케시에",
    "Moussa Diaby": "무사 디아비",
    "Sergej Milinkovic-Savic": "세르게이 밀린코비치사비치",
    "N'Golo Kante": "은골로 캉테",
    "Salem Al-Dawsari": "살렘 알다우사리",
    "Sultan Al-Ghannam": "술탄 알간남",
    "Ali Al-Bulaihi": "알리 알불라이히",
    "Joao Felix": "주앙 펠릭스",
    "Marcelo Brozovic": "마르첼로 브로조비치",
    "Yassine Bounou": "야신 부누",
    "Bono": "부누",
    "Fabinho": "파비뉴",
    "Jota": "조타",
    "Houssem Aouar": "우셈 아우아르",
    "Georginio Wijnaldum": "조르지니오 바이날둠",
    "Wu Lei": "우레이",
    "Zhang Yuning": "장위닝",
    "Wei Shihao": "웨이스하오",
    "Wang Dalei": "왕다레이",
    "Zhu Chenjie": "주천제",
    "Oscar": "오스카르",
    "Serginho": "세르지뉴",
    "Fernandinho": "페르난지뉴",
    "Leonardo": "레오나르두",
    "Aymen Hussein": "아이멘 후세인",
    "Ali Jasim": "알리 자심",
    "Mohanad Ali": "무한나드 알리",
    "Zaid Tahseen": "자이드 타흐신",
    "Muhsen Al-Ghassani": "무흐센 알가사니",
    "Issam Al-Sabhi": "이삼 알사브히",
    "Abdulaziz Al-Ghanim": "압둘아지즈 알가님",
    "Akram Afif": "아크람 아피프",
    "Almoez Ali": "알모에즈 알리",
    "Hassan Al-Haydos": "하산 알하이도스",
    "Ali Mabkhout": "알리 마브후트",
    "Mehdi Taremi": "메흐디 타레미",
    "Sardar Azmoun": "사르다르 아즈문",
    "Alireza Jahanbakhsh": "알리레자 자한바크시",
    "Takefusa Kubo": "구보 다케후사",
    "Kaoru Mitoma": "미토마 가오루",
    "Daichi Kamada": "가마다 다이치",
    "Wataru Endo": "엔도 와타루",
    "Ritsu Doan": "도안 리쓰",
    "Ayase Ueda": "우에다 아야세",
    "Takumi Minamino": "미나미노 다쿠미",
    "Hidemasa Morita": "모리타 히데마사",
    "Ko Itakura": "이타쿠라 고",
    "Zion Suzuki": "스즈키 자이온",
    "Pedro": "페드루",
    "Gabriel Barbosa": "가브리에우 바르보자",
    "Hulk": "훌크",
    "Paulinho": "파울리뉴",
    "Miguel Borja": "미겔 보르하",
    "Edinson Cavani": "에딘손 카바니",
    "Luis Suarez": "루이스 수아레스",
    "Everton Ribeiro": "에베르톤 히베이루",
    "Marcos Rojo": "마르코스 로호",
    "Neymar": "네이마르",
    "Memphis Depay": "멤피스 데파이",
    "Arrascaeta": "아라스카에타",
    "Gerson": "제르손",
    "Bruno Henrique": "브루누 엔히키",
    "Raphael Veiga": "하파에우 베이가",
    "Estevao": "에스테방",
    "Endrick": "엔드릭",
    "Vitor Roque": "비토르 호키",
    "Yuri Alberto": "유리 아우베르투",
    "Angel Correa": "앙헬 코레아",
    "Sergio Ramos": "세르히오 라모스",
    "James Rodriguez": "하메스 로드리게스",
    "Carlos Bacca": "카를로스 바카",
    "Juan Fernando Quintero": "후안 페르난도 킨테로",
    "Lionel Messi": "리오넬 메시",
    "Luis Suarez Miami": "루이스 수아레스",
    "Sergio Busquets": "세르히오 부스케츠",
    "Jordi Alba": "조르디 알바",
    "Son Heung Min LAFC": "손흥민",
    "Denis Bouanga": "드니 부앙가",
    "Hugo Lloris": "위고 요리스",
    "Thomas Muller": "토마스 뮐러",
    "Marco Reus": "마르코 로이스",
    "Lorenzo Insigne": "로렌초 인시녜",
    "Kim Min-Jae": "김민재",
    "Kim Minjae": "김민재",
    "Lee Kang-In": "이강인",
    "Lee Kangin": "이강인",
    "Hwang Hee-Chan": "황희찬",
    "Hwang Heechan": "황희찬",
    "Lee Jae-Sung": "이재성",
    "Hwang In-Beom": "황인범",
    "Oh Hyeon-Gyu": "오현규",
    "Cho Gue-Sung": "조규성",
    "Yang Min-Hyeok": "양민혁",
    "Bae Jun-Ho": "배준호",
    "Seol Young-Woo": "설영우",
    "Hong Hyun-Seok": "홍현석",
    "Jeong Woo-Yeong": "정우영",
    "Kim Ji-Soo": "김지수",
    "Um Ji-Sung": "엄지성",
    "Kwon Hyeok-Kyu": "권혁규",
    "Paik Seung-Ho": "백승호",
    "Kim Seung-Gyu": "김승규",
    "Jo Hyeon-Woo": "조현우",
    "Kim Young-Gwon": "김영권",
    "Kim Jin-Su": "김진수",
    "Park Yong-Woo": "박용우",
    "Lee Dong-Gyeong": "이동경",
    "Kim Moon-Hwan": "김문환",
    "Na Sang-Ho": "나상호",
    "Jung Sang-Bin": "정상빈",
    "Ali Lajami": "알리 라자미",
    "Saud Abdulhamid": "사우드 압둘하미드",
    "Mohammed Al-Owais": "모하메드 알오와이스",
    "Nawaf Al-Aqidi": "나와프 알아키디",
    "Hassan Tambakti": "하산 탐박티",
    "Abdulelah Al-Amri": "압둘엘라 알암리",
    "Saud Abdulhamid Roma": "사우드 압둘하미드",
    "Mohamed Kanno": "모하메드 칸노",
    "Nasser Al-Dawsari": "나세르 알다우사리",
    "Abdullah Radif": "압둘라 라디프",
    "Firas Al-Buraikan": "피라스 알부라이칸",
    "Saleh Al-Shehri": "살레 알셰흐리",
    "Musab Al-Juwair": "무사브 알주와이르",
    "Ayman Yahya": "아이만 야히아",
    "Marwan Al-Sahafi": "마르완 알사하피",
    "Ali Al-Hassan": "알리 알하산",
    "Abdulrahman Ghareeb": "압둘라흐만 가리브",
    "Sultan Al-Ghannam KSA": "술탄 알간남",
    "Yasser Al-Shahrani": "야세르 알샤흐라니",
    "Hattan Bahebri": "하탄 바헤브리",
    "Khalid Al-Ghannam": "칼리드 알간남",
    "Yousef Nasser": "유세프 나세르",
    "Eid Al-Rashidi": "에이드 알라시디",
    "Mohammed Daham": "모하메드 다함",
    "Hamad Al-Qallaf": "하마드 알칼라프",
    "Sultan Al-Enezi": "술탄 알에네지",
    "Abdullah Al-Bloushi": "압둘라 알블루시",
    "Rashid Bakheet": "라시드 바킷",
    "Zaid Tahseen Iraq": "자이드 타흐신",
    "Ibrahim Bayesh": "이브라힘 바예시",
    "Amir Al-Ammari": "아미르 알암마리",
    "Osama Rashid": "오사마 라시드",
    "Jalal Hassan": "잘랄 하산",
    "Rebin Sulaka": "레빈 술라카",
    "Merchas Doski": "메르차스 도스키",
    "Hussein Ali": "후세인 알리",
    "Youssef Amyn": "유세프 아민",
    "Ali Al-Hamadi": "알리 알하마디",
    "Aymen Hussein Iraq": "아이멘 후세인",
    "Harib Abdalla": "하리브 압달라",
    "Ali Al-Busaidi": "알리 알부사이디",
    "Jameel Al-Yahmadi": "자밀 알야흐마디",
    "Ibrahim Al-Mukhaini": "이브라힘 알무카이니",
    "Amjad Al-Harthi": "암자드 알하르시",
    "Ahmed Al-Kaabi": "아흐메드 알카비",
    "Abdullah Fawaz": "압둘라 파와즈",
    "Ali Al-Busaidi Oman": "알리 알부사이디",
    "Alisson Becker": "알리송",
    "Conor Bradley": "코너 브래들리",
    "Wataru Endo": "엔도 와타루",
    "Federico Chiesa": "페데리코 키에사",
    "Joe Gomez": "조 고메스",
    "Harvey Elliott": "하비 엘리엇",
    "Giorgi Mamardashvili": "조르지 마마르다슈빌리",
    "Rodri Hernandez": "로드리",
    "Nico Gonzalez": "니코 곤살레스",
    "Rico Lewis": "리코 루이스",
    "Stefan Ortega": "슈테판 오르테가",
    "Abdukodir Khusanov": "압두코디르 후사노프",
    "Vitor Reis": "비토르 헤이스",
    "Nico O'Reilly": "니코 오라일리",
    "Gabriel Jesus": "가브리엘 제주스",
    "Myles Lewis-Skelly": "마일스 루이스스켈리",
    "Ethan Nwaneri": "이선 은와네리",
    "Kepa Arrizabalaga": "케파 아리사발라가",
    "Christian Norgaard": "크리스티안 뇌르고르",
    "Piero Hincapie": "피에로 인카피에",
    "Wesley Fofana Chelsea": "웨슬리 포파나",
    "Marc Cucurella": "마르크 쿠쿠레야",
    "Malo Gusto": "말로 귀스토",
    "Romeo Lavia": "로메오 라비아",
    "Tosin Adarabioyo": "토신 아다라비오요",
    "Jamie Gittens": "제이미 기튼스",
    "Estevao Willian": "에스테방",
    "Filip Jorgensen": "필립 예르겐센",
    "Trevoh Chalobah": "트레보 찰로바",
    "Micky van de Ven Spurs": "미키 판더펜",
    "Pape Matar Sarr": "파페 마타르 사르",
    "Archie Gray": "아치 그레이",
    "Lucas Bergvall": "루카스 베리발",
    "Wilson Odobert": "윌슨 오도베르",
    "Mathys Tel": "마티스 텔",
    "Dominic Solanke Spurs": "도미닉 솔란케",
    "Mason Mount": "메이슨 마운트",
    "Diogo Dalot": "디오구 달롯",
    "Luke Shaw": "루크 쇼",
    "Noussair Mazraoui": "누사이르 마즈라위",
    "Casemiro": "카제미루",
    "Manuel Ugarte": "마누엘 우가르테",
    "Leny Yoro": "레니 요로",
    "Patrick Dorgu": "패트릭 도르구",
    "Joshua Zirkzee": "요슈아 지르크지",
    "Sandro Tonali Newcastle": "산드로 토날리",
    "Joelinton": "조엘린톤",
    "Lewis Hall": "루이스 홀",
    "Dan Burn": "댄 번",
    "Sven Botman": "스벤 보트만",
    "Jacob Murphy": "제이컵 머피",
    "Harvey Barnes": "하비 반스",
    "Fabian Schar": "파비안 셰어",
    "Kieran Trippier": "키어런 트리피어",
    "Youri Tielemans": "유리 틸레만스",
    "Boubacar Kamara": "부바카르 카마라",
    "Amadou Onana": "아마두 오나나",
    "Ezri Konsa": "에즈리 콘사",
    "Pau Torres": "파우 토레스",
    "Lucas Digne": "뤼카 디뉴",
    "Donyell Malen": "도니엘 말렌",
    "Nicolo Zaniolo": "니콜로 자니올로",
    "Jhon Duran": "욘 두란",
    "Ross Barkley": "로스 바클리",
    "Dango Ouattara": "당고 와타라",
    "Justin Kluivert": "유스틴 클라위버르트",
    "Milos Kerkez Bournemouth": "밀로시 케르케즈",
    "Illia Zabarnyi": "일리아 자바르니",
    "Ryan Christie": "라이언 크리스티",
    "Marcus Tavernier": "마커스 태버니어",
    "Kaoru Mitoma": "미토마 가오루",
    "Joao Pedro Brighton": "주앙 페드루",
    "Danny Welbeck": "대니 웰벡",
    "Georginio Rutter": "조르지뇨 뤼터",
    "Carlos Baleba": "카를로스 발레바",
    "Jan Paul van Hecke": "얀 파울 판헤케",
    "Bart Verbruggen": "바르트 페르브뤼헌",
    "Yankuba Minteh": "얀쿠바 민테",
    "Simon Adingra": "시몬 아딩그라",
    "Morgan Gibbs-White": "모건 깁스화이트",
    "Chris Wood": "크리스 우드",
    "Callum Hudson-Odoi": "칼럼 허드슨오도이",
    "Elliot Anderson": "엘리엇 앤더슨",
    "Nikola Milenkovic": "니콜라 밀렌코비치",
    "Murillo": "무릴루",
    "Ola Aina": "올라 아이나",
    "Matz Sels": "마츠 셀스",
    "Anthony Elanga": "앤서니 엘랑가",
    "Neco Williams": "네코 윌리엄스",
    "Adam Wharton": "애덤 워튼",
    "Daniel Munoz": "다니엘 무뇨스",
    "Tyrick Mitchell": "타이릭 미첼",
    "Ismaila Sarr": "이스마일라 사르",
    "Dean Henderson": "딘 헨더슨",
    "Chris Richards": "크리스 리처즈",
    "Maxence Lacroix": "막상스 라크루아",
    "Alex Iwobi": "알렉스 이워비",
    "Antoine Semenyo Bournemouth": "앙투안 세메뇨",
    "Raul Jimenez": "라울 히메네스",
    "Bernd Leno": "베른트 레노",
    "Sasa Lukic": "사샤 루키치",
    "Andreas Pereira": "안드레아스 페레이라",
    "Emile Smith Rowe": "에밀 스미스 로우",
    "Rodrigo Muniz": "호드리구 무니스",
    "Calvin Bassey": "캘빈 배시",
    "Antonee Robinson": "안토니 로빈슨",
    "Joachim Andersen": "요아킴 안데르센",
    "Ryan Sessegnon": "라이언 세세뇽",
    "Jordan Ayew": "조던 아예우",
    "Jarrad Branthwaite": "제라드 브랜스웨이트",
    "Jordan Pickford Everton": "조던 픽퍼드",
    "Iliman Ndiaye Everton": "일리망 은디아예",
    "Beto": "베투",
    "Dwight McNeil": "드와이트 맥닐",
    "James Tarkowski": "제임스 타르코스키",
    "Vitalii Mykolenko": "비탈리 미콜렌코",
    "Idrissa Gueye": "이드리사 게예",
    "Jack Grealish": "잭 그릴리시",
    "Mateo Kovacic City": "마테오 코바치치",
    "Jeremy Doku City": "제레미 도쿠",
    "Thibaut Courtois Real": "티보 쿠르투아",
    "Raul Asencio": "라울 아센시오",
    "Ferland Mendy": "페를랑 멘디",
    "Endrick Felipe": "엔드릭",
    "Gonzalo Garcia": "곤살로 가르시아",
    "Jacobo Ramon": "하코보 라몬",
    "Ronald Araujo Barca": "로날드 아라우호",
    "Inigo Martinez": "이니고 마르티네스",
    "Andreas Christensen": "안드레아스 크리스텐센",
    "Eric Garcia": "에릭 가르시아",
    "Fermin Lopez": "페르민 로페스",
    "Marc Casado": "마르크 카사도",
    "Hector Fort": "엑토르 포르트",
    "Wojciech Szczesny": "보이치에흐 슈체스니",
    "Gerard Martin": "제라르드 마르틴",
    "Pablo Barrios": "파블로 바리오스",
    "Rodrigo De Paul": "로드리고 데파울",
    "Conor Gallagher": "코너 갤러거",
    "Robin Le Normand": "로뱅 르노르망",
    "Clement Lenglet": "클레망 랑글레",
    "Samuel Lino": "사무엘 리누",
    "Giuliano Simeone": "줄리아노 시메오네",
    "Marcos Llorente": "마르코스 요렌테",
    "Axel Witsel": "악셀 비첼",
    "Aitor Paredes": "아이토르 파레데스",
    "Oihan Sancet Bilbao": "오이안 산세트",
    "Alex Berenguer": "알렉스 베렝게르",
    "Mikel Jauregizar": "미켈 하우레기사르",
    "Dani Vivian": "다니 비비안",
    "Yuri Berchiche": "유리 베르치체",
    "Brais Mendez": "브라이스 멘데스",
    "Sergio Gomez": "세르히오 고메스",
    "Luka Sucic": "루카 수치치",
    "Sheraldo Becker": "셰랄도 베커",
    "Umar Sadiq": "우마르 사디크",
    "Pablo Fornals": "파블로 포르날스",
    "Giovani Lo Celso Betis": "조바니 로셀소",
    "Cedric Bakambu": "세드리크 바캄부",
    "Abde Ezzalzouli": "압데 에살줄리",
    "Marc Bartra": "마르크 바르트라",
    "Hector Bellerin": "엑토르 베예린",
    "Aitor Ruibal": "아이토르 루이발",
    "Alvaro Garcia": "알바로 가르시아",
    "Isi Palazon": "이시 팔라손",
    "Augusto Batalla": "아우구스토 바타야",
    "Florian Lejeune": "플로리안 르죈",
    "Oscar Valentin": "오스카르 발렌틴",
    "Unai Lopez": "우나이 로페스",
    "Ante Budimir Osasuna": "안테 부디미르",
    "Sergio Herrera": "세르히오 에레라",
    "Lucas Torro": "루카스 토로",
    "Bryan Zaragoza": "브라이언 사라고사",
    "Alex Baena": "알렉스 바에나",
    "Dani Parejo": "다니 파레호",
    "Ayoze Perez": "아요세 페레스",
    "Santi Comesana": "산티 코메사냐",
    "Logan Costa": "로간 코스타",
    "Luiz Junior": "루이스 주니오르",
    "Sergi Cardona": "세르지 카르도나",
    "Thierno Barry": "티에르노 바리",
    "Denzel Dumfries": "덴절 둠프리스",
    "Carlos Augusto": "카를로스 아우구스투",
    "Davide Frattesi": "다비데 프라테시",
    "Henrikh Mkhitaryan": "헨리크 미키타리안",
    "Francesco Acerbi": "프란체스코 아체르비",
    "Stefan de Vrij": "스테판 더프레이",
    "Yann Bisseck": "얀 비세크",
    "Piotr Zielinski": "피오트르 지엘린스키",
    "Mehdi Taremi Inter": "메흐디 타레미",
    "Alessandro Bastoni Inter": "알레산드로 바스토니",
    "Matteo Darmian": "마테오 다르미안",
    "Strahinja Pavlovic": "스트라히냐 파블로비치",
    "Malick Thiaw": "말리크 티아우",
    "Youssouf Fofana": "유수프 포파나",
    "Ruben Loftus-Cheek": "루벤 로프터스치크",
    "Samuel Chukwueze": "새뮤얼 추쿠에제",
    "Alvaro Morata": "알바로 모라타",
    "Santiago Gimenez Milan": "산티아고 히메네스",
    "Emerson Royal": "에메르송 로얄",
    "Alex Jimenez": "알렉스 히메네스",
    "Andre Frank Zambo Anguissa": "프랑크 잠보 앙기사",
    "Stanislav Lobotka": "스타니슬라프 로보트카",
    "Amir Rrahmani": "아미르 라흐마니",
    "Alessandro Buongiorno": "알레산드로 부온조르노",
    "Matteo Politano": "마테오 폴리타노",
    "David Neres": "다비드 네리스",
    "Billy Gilmour": "빌리 길모어",
    "Leonardo Spinazzola": "레오나르도 스피나촐라",
    "Manuel Locatelli Juve": "마누엘 로카텔리",
    "Teun Koopmeiners": "퇸 코프메이네르스",
    "Weston McKennie": "웨스턴 매케니",
    "Federico Gatti": "페데리코 가티",
    "Gleison Bremer": "글레이송 브레메르",
    "Andrea Cambiaso": "안드레아 캄비아소",
    "Pierre Kalulu": "피에르 칼룰루",
    "Nicolas Gonzalez Juve": "니콜라스 곤살레스",
    "Randal Kolo Muani": "랑달 콜로 무아니",
    "Lorenzo Pellegrini": "로렌초 펠레그리니",
    "Bryan Cristante": "브라이언 크리스탄테",
    "Gianluca Mancini": "잔루카 만치니",
    "Mats Hummels": "마츠 훔멜스",
    "Angelino": "안젤리뇨",
    "Matias Soule": "마티아스 술레",
    "Eldor Shomurodov": "엘도르 쇼무로도프",
    "Nicolo Zaniolo Atalanta": "니콜로 자니올로",
    "Marten de Roon": "마르턴 더론",
    "Eder Alvarez": "에데르손",
    "Isak Hien": "이사크 히엔",
    "Sead Kolasinac": "세아드 콜라시나츠",
    "Davide Zappacosta": "다비데 자파코스타",
    "Lazar Samardzic": "라자르 사마르지치",
    "Nicolo Fagioli": "니콜로 파졸리",
    "Moise Kean Fiorentina": "모이즈 킨",
    "David De Gea": "다비드 데헤아",
    "Rolando Mandragora": "롤란도 만드라고라",
    "Robin Gosens": "로빈 고센스",
    "Mattia Zaccagni": "마티아 차카니",
    "Taty Castellanos": "발렌틴 카스테야노스",
    "Nuno Tavares": "누누 타바레스",
    "Alessio Romagnoli": "알레시오 로마뇰리",
    "Ivan Provedel": "이반 프로베델",
    "Gustav Isaksen": "구스타브 이삭센",
    "Konrad Laimer": "콘라트 라이머",
    "Josip Stanisic": "요시프 스타니시치",
    "Kim Min-Jae Bayern": "김민재",
    "Leroy Sane": "르로이 자네",
    "Raphael Guerreiro": "하파엘 게헤이루",
    "Sven Ulreich": "스벤 울라이히",
    "Aleksandar Pavlovic": "알렉산다르 파블로비치",
    "Emre Can": "에므레 잔",
    "Nico Schlotterbeck": "니코 슐로터베크",
    "Waldemar Anton": "발데마어 안톤",
    "Ramy Bensebaini": "라미 벤세바이니",
    "Maximilian Beier": "막시밀리안 바이어",
    "Jobe Bellingham": "조비 벨링엄",
    "Daniel Svensson": "다니엘 스벤손",
    "Yan Couto": "얀 코투",
    "Edmond Tapsoba": "에드몽 탑소바",
    "Robert Andrich": "로베르트 안드리히",
    "Exequiel Palacios": "에세키엘 팔라시오스",
    "Granit Xhaka": "그라니트 자카",
    "Amine Adli": "아민 아들리",
    "Nathan Tella": "네이선 텔라",
    "Lukas Hradecky": "루카스 흐라데츠키",
    "Jonas Hofmann Leverkusen": "요나스 호프만",
    "Aleix Garcia": "알레익스 가르시아",
    "Ritsu Doan Frankfurt": "도안 리쓰",
    "Ellyes Skhiri": "엘리에스 스키리",
    "Robin Koch": "로빈 코흐",
    "Arthur Theate": "아르튀르 테아트",
    "Kevin Trapp": "케빈 트랍",
    "Can Uzun": "잔 우준",
    "Jean-Matteo Bahoya": "장마테오 바오야",
    "Nick Woltemade Stuttgart": "닉 볼테마데",
    "Atakan Karazor": "아타칸 카라조르",
    "Chris Fuhrich": "크리스 퓌리히",
    "Alexander Nubel": "알렉산더 뉘벨",
    "Jeff Chabot": "제프 샤보",
    "Enzo Millot": "엔소 미요",
    "Florian Neuhaus": "플로리안 노이하우스",
    "Rocco Reitz": "로코 라이츠",
    "Kevin Stoger": "케빈 슈퇴거",
    "Moritz Nicolas": "모리츠 니콜라스",
    "Ko Itakura Gladbach": "이타쿠라 고",
    "Julian Weigl": "율리안 바이글",
    "Xaver Schlager": "자버 슐라거",
    "Benjamin Sesko": "벤야민 셰슈코",
    "Lois Openda": "로이스 오펜다",
    "Willi Orban": "빌리 오르반",
    "David Raum": "다비트 라움",
    "Peter Gulacsi": "페테르 굴라치",
    "Antonio Nusa": "안토니오 누사",
    "Nicolas Kuhn": "니콜라스 퀸",
    "Christoph Baumgartner": "크리스토프 바움가르트너",
    "Warren Zaire-Emery": "바랑 자이르에메리",
    "Willian Pacho": "윌리안 파초",
    "Lucas Hernandez": "뤼카 에르난데스",
    "Senny Mayulu": "세니 마율루",
    "Goncalo Ramos": "곤살루 하무스",
    "Lee Kang-In PSG": "이강인",
    "Matvey Safonov": "마트베이 사포노프",
    "Ibrahim Mbaye": "이브라힘 음바예",
    "Quentin Ndjantou": "캉탱 은장투",
    "Geronimo Rulli": "헤로니모 룰리",
    "Leonardo Balerdi": "레오나르도 발레르디",
    "Ulisses Garcia": "울리세스 가르시아",
    "Bilal Nadir": "빌랄 나디르",
    "Neal Maupay": "닐 모페이",
    "Jonathan Rowe": "조너선 로",
    "Denis Zakaria": "드니 자카리아",
    "Maghnes Akliouche": "마그네스 아클리우슈",
    "Takumi Minamino Monaco": "미나미노 다쿠미",
    "Eliesse Ben Seghir": "엘리에스 벤세기르",
    "Mohammed Salisu": "모하메드 살리수",
    "Thilo Kehrer": "틸로 케러",
    "Philipp Kohn": "필리프 쾨른",
    "Lucas Chevalier Lille": "뤼카 슈발리에",
    "Benjamin Andre": "뱅자맹 앙드레",
    "Hakon Haraldsson": "호콘 하랄손",
    "Edon Zhegrova": "에돈 제그로바",
    "Ayyoub Bouaddi": "아유브 부아디",
    "Alexsandro Ribeiro": "알렉산드루",
    "Bafode Diakite": "바포데 디아키테",
    "Rayan Cherki": "라얀 셰르키",
    "Corentin Tolisso": "코랑탱 톨리소",
    "Nemanja Matic": "네마냐 마티치",
    "Malick Fofana": "말리크 포파나",
    "Lucas Perri": "루카스 페리",
    "Nicolas Tagliafico": "니콜라스 타글리아피코",
    "Moussa Niakhate": "무사 니아카테",
    "Ludovic Ajorque": "뤼도비크 아조르크",
    "Emanuel Emegha Strasbourg": "에마뉘엘 에메가",
    "Habib Diarra": "아비브 디아라",
    "Andrey Santos": "안드레이 산투스",
    "Dilane Bakwa": "딜란 바크와",
    "Takumi Minamino": "미나미노 다쿠미",
    "Shuto Machino": "마치노 슈토",
    "Mao Hosoya": "호소야 마오",
    "Koki Ogawa": "오가와 코키",
    "Yukinari Sugawara": "스가와라 유키나리",
    "Seiya Maikuma": "마이쿠마 세이야",
    "Yuki Soma": "소마 유키",
    "Kyogo Furuhashi": "후루하시 쿄고",
    "Junya Ito": "이토 준야",
    "Ao Tanaka": "다나카 아오",
    "Keito Nakamura": "나카무라 케이토",
    "Reo Hatate": "하타테 레오",
    "Daizen Maeda": "마에다 다이젠",
    # ---- MLS 주요 선수 ----
    "Heung-Min Son": "손흥민", "Son Heung-Min": "손흥민", "Heung Min Son": "손흥민",
    "Riqui Puig": "리키 푸치", "Joseph Paintsil": "조지프 페인칠", "Miguel Almiron": "미겔 알미론",
    "Jordan Morris": "조던 모리스", "Albert Rusnak": "알베르트 루스나크", "Diego Rossi": "디에고 로시",
    "Evander": "에반데르", "Luca Orellano": "루카 오레야노", "Alonso Martinez": "알론소 마르티네스",
    "Hany Mukhtar": "하니 무크타르", "Sam Surridge": "샘 서리지", "Tai Baribo": "타이 바리보",
    "Brandon Vazquez": "브랜던 바스케스", "Wilfried Zaha": "윌프리드 자하",
    "Federico Bernardeschi": "페데리코 베르나르데스키", "Lorenzo Insigne": "로렌초 인시녜",
    "Martin Ojeda": "마르틴 오헤다", "Luis Muriel": "루이스 무리엘", "Emil Forsberg": "에밀 포르스베리",
    "Hirving Lozano": "이르빙 로사노", "Anders Dreyer": "안데르스 드레위에르", "Diego Luna": "디에고 루나",
    "Petar Musa": "페타르 무사", "Dejan Joveljic": "데얀 요벨리치", "Erik Thommy": "에리크 토미",
    "Carles Gil": "카를레스 힐", "Christian Benteke": "크리스티안 벤테케", "Cristian Arango": "크리스티안 아랑고",
    "Josef Martinez": "요세프 마르티네스", "Jonathan Bamba": "조나탕 밤바", "Hugo Cuypers": "위고 카위퍼르스",
    "Ryan Gauld": "라이언 골드", "Brian White": "브라이언 화이트", "Rafael Navarro": "하파에우 나바루",
    "Kelvin Yeboah": "켈빈 예보아", "Facundo Torres": "파쿤도 토레스", "Maximiliano Falcon": "막시밀리아노 팔콘",
    "Sergio Canales": "세르히오 카날레스", "Cucho Hernandez": "쿠초 에르난데스", "Thiago Almada": "티아고 알마다",
    "Julian Gressel": "율리안 그레셀", "Walker Zimmerman": "워커 지머먼", "Matt Turner": "맷 터너",
    "Zack Steffen": "잭 스테펜", "Tyler Adams": "타일러 애덤스", "Gio Reyna": "조반니 레이나",
    "Giovanni Reyna": "조반니 레이나", "Folarin Balogun": "폴라린 발로건", "Yunus Musah": "유누스 무사",
    "Sergino Dest": "세르지뇨 데스트", "Ricardo Pepi": "리카르도 페피", "Malik Tillman": "말리크 틸먼",
    "Johnny Cardoso": "조니 카르도주", "Marco Delgado": "마르코 델가도", "Denis Bouanga": "드니 부앙가",
    "Nathan Ordaz": "네이선 오르다스", "Kevin Denkey": "케빈 뎅케이", "Sebastian Driussi": "세바스티안 드리우시",
    "Emmanuel Latte Lath": "에마뉘엘 라테 라트", "Jesus Ferreira": "헤수스 페레이라",
    "Christian Ramirez": "크리스티안 라미레스", "Djordje Mihailovic": "조르제 미하일로비치",
    "Patrick Agyemang": "패트릭 아제망", "Tim Ream": "팀 림", "Jack McGlynn": "잭 매글린",
    "Paxten Aaronson": "팩스턴 애런슨", "Brenden Aaronson": "브렌던 애런슨", "Josh Sargent": "조시 사전트",
    "Haji Wright": "하지 라이트", "Luca de la Torre": "루카 데라토레", "Tanner Tessmann": "태너 테스먼"
}

_PLAYER_TABLE = {}
for _en, _ko in PLAYERS.items():
    _PLAYER_TABLE.setdefault(_key(_en), _ko)

_PLAYER_LAST = {}
for _en, _ko in PLAYERS.items():                      # 성으로도 맞추되, 성이 겹치면 쓰지 않는다
    _w = _key(_en).split()
    if not _w:
        continue
    _last, _first = _w[-1], (_w[0][0] if len(_w) > 1 else "")
    if _last in _PLAYER_LAST and (_PLAYER_LAST[_last] or ("", ""))[0] != _ko:
        _PLAYER_LAST[_last] = None                    # 같은 성이 둘 이상 → 쓰지 않음
    else:
        _PLAYER_LAST.setdefault(_last, (_ko, _first))


# ---------------------------------------------------------------- 일본 선수 이름: 로마자 -> 한글 (사전 없이 규칙으로)
# 외래어 표기법(일본어)을 따른다.
#   · か·た행은 어두에 ㄱ·ㄷ, 어중에 ㅋ·ㅌ  (Tanaka -> 다나카)
#   · つ는 '쓰'  (Matsumoto -> 마쓰모토)
#   · 장음은 적지 않는다  (Kouta -> 고타)
#   · っ은 ㅅ 받침(Sapporo -> 삿포로), ん은 ㄴ 받침(Shinji -> 신지)
# 값은 (어두, 어중) 쌍.
_JP = {
    "a": ("아", "아"), "i": ("이", "이"), "u": ("우", "우"), "e": ("에", "에"), "o": ("오", "오"),
    "ka": ("가", "카"), "ki": ("기", "키"), "ku": ("구", "쿠"), "ke": ("게", "케"), "ko": ("고", "코"),
    "kya": ("갸", "캬"), "kyu": ("규", "큐"), "kyo": ("교", "쿄"),
    "ga": ("가", "가"), "gi": ("기", "기"), "gu": ("구", "구"), "ge": ("게", "게"), "go": ("고", "고"),
    "gya": ("갸", "갸"), "gyu": ("규", "규"), "gyo": ("교", "교"),
    "sa": ("사", "사"), "shi": ("시", "시"), "su": ("스", "스"), "se": ("세", "세"), "so": ("소", "소"),
    "sha": ("샤", "샤"), "shu": ("슈", "슈"), "sho": ("쇼", "쇼"),
    "za": ("자", "자"), "ji": ("지", "지"), "zu": ("즈", "즈"), "ze": ("제", "제"), "zo": ("조", "조"),
    "ja": ("자", "자"), "ju": ("주", "주"), "jo": ("조", "조"), "jya": ("자", "자"), "jyu": ("주", "주"), "jyo": ("조", "조"),
    "ta": ("다", "타"), "chi": ("지", "치"), "tsu": ("쓰", "쓰"), "te": ("데", "테"), "to": ("도", "토"),
    "cha": ("자", "차"), "chu": ("주", "추"), "cho": ("조", "초"),
    "da": ("다", "다"), "de": ("데", "데"), "do": ("도", "도"),
    "na": ("나", "나"), "ni": ("니", "니"), "nu": ("누", "누"), "ne": ("네", "네"), "no": ("노", "노"),
    "nya": ("냐", "냐"), "nyu": ("뉴", "뉴"), "nyo": ("뇨", "뇨"),
    "ha": ("하", "하"), "hi": ("히", "히"), "fu": ("후", "후"), "he": ("헤", "헤"), "ho": ("호", "호"),
    "hya": ("햐", "햐"), "hyu": ("휴", "휴"), "hyo": ("효", "효"),
    "ba": ("바", "바"), "bi": ("비", "비"), "bu": ("부", "부"), "be": ("베", "베"), "bo": ("보", "보"),
    "bya": ("뱌", "뱌"), "byu": ("뷰", "뷰"), "byo": ("뵤", "뵤"),
    "pa": ("파", "파"), "pi": ("피", "피"), "pu": ("푸", "푸"), "pe": ("페", "페"), "po": ("포", "포"),
    "pya": ("퍄", "퍄"), "pyu": ("퓨", "퓨"), "pyo": ("표", "표"),
    "ma": ("마", "마"), "mi": ("미", "미"), "mu": ("무", "무"), "me": ("메", "메"), "mo": ("모", "모"),
    "mya": ("먀", "먀"), "myu": ("뮤", "뮤"), "myo": ("묘", "묘"),
    "ya": ("야", "야"), "yu": ("유", "유"), "yo": ("요", "요"),
    "ra": ("라", "라"), "ri": ("리", "리"), "ru": ("루", "루"), "re": ("레", "레"), "ro": ("로", "로"),
    "rya": ("랴", "랴"), "ryu": ("류", "류"), "ryo": ("료", "료"),
    "wa": ("와", "와"), "wo": ("오", "오"),
    "va": ("바", "바"), "vi": ("비", "비"), "vu": ("부", "부"), "ve": ("베", "베"), "vo": ("보", "보"),
    "fa": ("파", "파"), "fi": ("피", "피"), "fe": ("페", "페"), "fo": ("포", "포"),
    "je": ("제", "제"), "she": ("셰", "셰"), "che": ("체", "체"),
}
_JP_CONS = "kgsztdnhfbpmyrwcj"
_JONG_N, _JONG_S = 4, 19                                    # ㄴ, ㅅ 받침


def _add_final(text, jong):
    """마지막 글자에 받침을 붙인다 (이미 받침이 있으면 그대로)."""
    if not text:
        return text
    code = ord(text[-1]) - 0xAC00
    if not (0 <= code < 11172) or code % 28:
        return text
    return text[:-1] + chr(ord(text[-1]) + jong)


def _jp_word(w):
    """로마자 한 낱말 -> 한글. 일본어로 읽을 수 없으면 None (브라질·유럽 이름 걸러내기)."""
    s = re.sub(r"oh(?=[kgsztdnhbpmyrw])", "o", w)           # Ohtani -> Otani
    s = re.sub(r"ou(?!e)", "o", s)                           # Kouta -> 고타. 단 Inoue(井上)는 '우'를 살린다
    s = s.replace("oo", "o").replace("nn", "n")
    # 'uu'는 건드리지 않는다: 출처가 장음을 겹쳐 쓰지 않아서 Matsuura(松浦) 같은 두 박자일 때가 많다
    out, i, head = "", 0, True
    while i < len(s):
        c = s[i]
        if s[i:i + 3] == "tch" or (c in _JP_CONS and c != "n" and s[i:i + 2] == c + c):
            if not out:                                      # 낱말 첫머리에 촉음은 없다
                return None
            out = _add_final(out, _JONG_S)
            i += 1
            continue
        # ん + や행·いち는 헵번식에서 아포스트로피를 빼고 적는다 (Junya=じゅんや, Kenichi=けんいち)
        nn = c == "n" and bool(out) and (s[i + 1:i + 2] == "y" or re.match(r"ichi(rou?)?$", s[i + 1:]))
        if c == "n" and (nn or i + 1 >= len(s) or s[i + 1] not in "aiueoy"):
            if not out:
                return None
            out = _add_final(out, _JONG_N)
            i += 1
            head = False
            continue
        for ln in (3, 2, 1):
            tok = s[i:i + ln]
            if tok in _JP:
                out += _JP[tok][0 if head else 1]
                i += ln
                head = False
                break
        else:
            return None
    return out or None


def jp_player(name):
    """일본식 로마자 이름이면 '성 이름' 순서의 한글로. 아니면 None.
    풋몹·ESPN은 '이름 성' 순서로 주므로 뒤집는다 (Daizen Maeda -> 마에다 다이젠)."""
    raw = str(name or "")
    if not raw or re.search(r"[가-힣]", raw):
        return None
    words = _key(raw).split()
    if not 1 <= len(words) <= 2 or any(len(w) < 2 for w in words):
        return None
    parts = [_jp_word(w) for w in words]
    if not all(parts):
        return None
    return parts[-1] + (" " + parts[0] if len(parts) == 2 else "")


def ko_player(name, jp=False):
    """영어 선수 이름 -> 한국어 (사전에 없으면 원래 이름). 이미 한국어면 그대로.
    철자가 조금 달라도(Aymen/Ayman) 성이 하나뿐이고 이름 첫 글자가 같으면 바꾼다.
    jp=True(일본 리그)면 사전에 없을 때 로마자를 규칙으로 읽는다."""
    raw = str(name or "")
    if not raw or re.search(r"[가-힣]", raw):
        return raw
    k = _key(raw)
    if k in _PLAYER_TABLE:
        return _PLAYER_TABLE[k]
    words = k.split()
    if not words:
        return raw
    hit = _PLAYER_LAST.get(words[-1])
    if hit:
        ko, first = hit
        if len(words) == 1 or not first or words[0][0] == first:
            return ko
    if jp:
        return jp_player(raw) or raw
    return raw
